_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.11.3
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": linux-x86_64
